### ISSUE TITLE
/api/passwordless/login not returning 'context'

### ISSUE THREAD

**Issue by chan-fullstack** [kucherenko/strapi-plugin-passwordless#6] opened 2022-06-01 11:42 UTC
### Issue
"context" remains empty even though it exists in the database.

The culprit is this line: https://github.com/kucherenko/strapi-plugin-passwordless/blob/750f4f50b660b626b3cd6d739305d635d40cc2cc/server/controllers/auth.js#L64

It throws a SyntaxError:
![image](https://user-images.githubusercontent.com/61461187/171395775-d6187e57-d6ef-49dc-b4cd-dfbc6293e88e.png)
_which is due to parsing a non-JSON entity_

Proposed solution: 
Update line to `context = JSON.parse(JSON.stringify(token.context))`

**Comment by kucherenko** [comment] 2022-06-01 12:20
Thank you for the issue, investigating

**Comment by rndexe** [comment] 2022-06-04 16:47
Faced the same issue, ended up using JSON.stringify on the context object before post request.

**Comment by kucherenko** [comment] 2022-06-29 13:39
I've investigated the issue and can't reproduce it, what were the steps:
 - call send link service
```
POST /api/passwordless/send-link

Body:
{
  "email": "user@email.com",
  "username": "John Bull",
  "context": { 
    "test": "test context"
  }
}

```
- call login service
```
GET /api/passwordless/login?loginToken=my_token_from_email
```
The result:
```json
{
    "jwt": "my jwt token",
    "user": {
        "id": 1,
        "username": "John Bull",
        "email": "user@email.com",
        "provider": null,
        "confirmed": true,
        "blocked": false,
        "createdAt": "2022-06-29T13:18:51.909Z",
        "updatedAt": "2022-06-29T13:20:36.033Z"
    },
    "context": {
        "test": "test context"
    }
}
```

**Comment by kucherenko** [comment] 2022-06-29 13:40
So, looks like I can't reproduce the issue, and going to close it

**Closed as completed by kucherenko** 2022-06-29 13:40 UTC
